### ISSUE TITLE
Empty BlockchainHead returned

### ISSUE THREAD

**Issue by safeith** [ConsenSys/btcrelay-fetchd#12]
I run Ethereum with this command

geth --fast --cache=512 --unlock dae251a771a980028b2c6b11f1da34785c035cb5 --password /root/password --rpc

And run btcrelay-fetchd with this command

python fetchd.py -s 0xdae251a771a980028b2c6b11f1da34785c035cb5 -r 0x41f274c0023f83391de4e0733c609df5a124c3d4 -n btc --rpcPort 8545 --fetch -d --gasPrice 200000000000

But i get this out put 

fetchd using PyEPM 1.0.2
feeVTX: 0
feeRecipient: 0xdae251a771a980028b2c6b11f1da34785c035cb5
Empty BlockchainHead returned.
Retry in 1min

I am using Ubuntu 16.04.1 LTS

Best Regards

**Comment by ethers** [comment]
Thank you for the report.  This is caused by #13
