### ISSUE TITLE
Ubuntu 14.04 Use of closed network connection

### ISSUE THREAD

**Issue by reemuru** [ConsenSys/btcrelay-fetchd#3]
RPC is enabled and coinbase unlocked. Here is the output:

(ETHEREUM)admin@localhost:~/BTCrelay/btcrelay-fetchd-master$ python fetchd.py -s 0x39a03f5528ac914f54b6065828fb994eb5aa5c98 -r 0x23d0ff718861979e08db52627941eb0f1f3783b9 -n btc --rpcPort 8545 --fetch --gasPrice 500000000000 >> ~/btcrelaytest.log 
fetchd using PyEPM 1.0.2
feeVTX: 0
Starting new HTTP connection (1): 127.0.0.1
Starting new HTTP connection (1): 127.0.0.1
BTC BlockchainHead: 00000000000000000466fe013c66655cc5363c00abf7b19d0ad9989dd70b5405
Starting new HTTP connection (1): 127.0.0.1
Starting new HTTP connection (1): 127.0.0.1
Starting new HTTP connection (1): 127.0.0.1
Starting new HTTP connection (1): 127.0.0.1
@@@ startFetch: 401496 actualHeight: 401536
## @@@ numChunk: 8 leftoverToFetch: 41

@@@ 401496: 0400000005540bd79d98d90a9db1f7ab003c36c55c65663c01fe660400000000000000004778c3cc523061b5a9873c131b71a6509d6c2b837bda72ee7c70b54062013e4e95d4dc56a8f006180a7fb861
@@@ 401497: 04000000cd7670fa0c4e5fdb0adb42c535fff3f4e32a966069c557010000000000000000e3256216f8e2caa7ac8ea4896fb0c609504502258f83f2f53b013625eb1afb94f9dcdc56a8f00618ce8c9041
@@@ 401498: 040000005f23716bb336791692184c0ea5747bda99938f997510db060000000000000000a9efcfdaea94721b5afc2fa68e0fcdd86b5ec01a5676dae280869411f8b2016ca1dedc56a8f0061871cb858a
@@@ 401499: 040000007fe9888eb6ee9cf8fd6762a1a2f453855cd3d99c0956d504000000000000000086aeb8e1bb5521b0336476e848c060fa211ce166cd4296625ac237415ca4e6b53fe0dc56a8f0061850ff79f3
@@@ 401500: 040000006e1dfa3421b61ade1f7c560e6289428171ae084e25a8af0500000000000000008c56015ca5bb6998fce1985d72b0165c26f926c0174ef995adfa09244ec06635a8e0dc56a8f00618a095bbdb
## Starting new HTTP connection (1): 127.0.0.1

txCount: 1048576
hashOne: 00000000000000000157c56960962ae3f4f3ff35c542db0adb5f4e0cfa7076cd
hashLast: 000000000000000006319cddc3aa4fb6d54d38da793e77e3c8ea19ab415198b4
firstH: 0400000005540bd79d98d90a9db1f7ab003c36c55c65663c01fe660400000000000000004778c3cc523061b5a9873c131b71a6509d6c2b837bda72ee7c70b54062013e4e95d4dc56a8f006180a7fb861
lastH: 040000006e1dfa3421b61ade1f7c560e6289428171ae084e25a8af0500000000000000008c56015ca5bb6998fce1985d72b0165c26f926c0174ef995adfa09244ec06635a8e0dc56a8f00618a095bbdb
Starting new HTTP connection (1): 127.0.0.1
    Gas price: 0.0200 szabo \* 1.0000
    Our price: 20,000,000,000
Starting new HTTP connection (1): 127.0.0.1
Traceback (most recent call last):
  File "fetchd.py", line 280, in <module>
    main()
  File "fetchd.py", line 75, in main
    run(feeVerifyTx, doFetch=args.fetch, network=args.network, startBlock=args.startBlock)
  File "fetchd.py", line 164, in run
    fetchHeaders(instance.heightToStartFetch, chunkSize, numChunk, feeVerifyTx, network=network)
  File "fetchd.py", line 180, in fetchHeaders
    storeHeaders(strings.decode('hex'), chunkSize, feeVerifyTx)
  File "fetchd.py", line 225, in storeHeaders
    txHash = instance.transact(instance.relayContract, sig=sig, data=data, gas=gas, value=value)
  File "/usr/local/lib/python2.7/dist-packages/pyepm/api.py", line 263, in transact
    return self._rpc_post('eth_sendTransaction', params)
  File "/usr/local/lib/python2.7/dist-packages/pyepm/api.py", line 93, in _rpc_post
    raise ApiException(response['error']['code'], response['error']['message'])
pyepm.api.ApiException: code=-32603, message="Transaction not confirmed"

**In geth console**

I0307 16:26:14.729086    7295 remote_frontend.go:116] Unable to send tx confirmation request to agent - write unix /home/admin/.ethereum/geth.ipc->@: use of closed network connectio

**Comment by ethers** [comment]
This appears to be an issue with connectivity to Geth being lost.  There have been some updates for the production launch and please try latest version of btcrelay-fetchd.
