### ISSUE TITLE
Setting Fee

### ISSUE THREAD

**Issue by santyr** [ConsenSys/btcrelay-fetchd#5]
Does one use the --feeVTX flag to set a fee with BTCrelay (--feeVTX 1000000000000000)?  So Far I've only paid out gas costs and am wondering if I'm running this correctly, since I'm not recieveing any reward:

python fetchd.py -s 0xMyAddress -r 0x41f274c0023f83391de4e0733c609df5a124c3d4 -n btc --rpcPort 8545 --fetch -d --gasPrice 200000000000 --feeVTX 1000000000000000 --feeRecipient 0xMyAddress

**Comment by gcarq** [comment]
Same here. `python2 fetchd.py -s 0xaddr -r 0x41f274c0023f83391de4e0733c609df5a124c3d4 -n btc --rpcPort 8545 --fetch --gasPrice 30000000000 --feeVTX 900000000000000 -d` does not give any reward.

**Comment by ethers** [comment]
@gcarq 
From what I'm seeing from the address you provided, there are a few headers where the address submitted a header that already exists: so the address won't become the feeRecipient for such headers. However, you have submitted some headers successfully, for example it seems your address is the feeRecipient for (bitcoin) block 410110, so you could try verifying one of these transactions: https://blockchain.info/block/0000000000000000012ebd2f1610e0b84cce658c92b0ba3c7ee0839fbd406615
If you try that, pls provide the ETH transaction id if it doesn't work

Making this type of call shows that you're the feeRecipient of block 410110:
btcrelaycontract.getFeeRecipient.call('0x0000000000000000012ebd2f1610e0b84cce658c92b0ba3c7ee0839fbd406615').toString(16)
"f7272a160f6607a4ab327b5cf2e6c1aff2b51b76"

@santyr Which block are you making a verifyTx/relayTx call against?  Can you check that you are the feeRecipient of the block, or try on a block where you are the feeRecipient?  Above is an example of calling getFeeRecipient

**Comment by liberspirita** [comment]
Same as gcard : each time i relay, i lost gas without winning fee ...

python fetchd.py -s 0x731f48fb82e3aa0085a39775fe6987f943b05362 -r 0x41f274c0023f83391de4e0733c609df5a124c3d4 -n btc --rpcPort 8545 --fetch -d --gasPrice 200000000000 --feeVTX 100000000000 --feeRecipient 0x731f48fb82e3aa0085a39775fe6987f943b05362

store header txHash: 0xf55b6ab2550fe9f648f4e12259e6699e07191bd1dc3a4d3468f6875aa2bda79a
    Waiting for transaction (retrying in 30s).Starting new HTTP connection (1): 127.0.0.1
 Took 0s
store header pendingblock txResult: True
    Waiting for transaction to be mined (retrying in 60s).Starting new HTTP connection (1): 127.0.0.1
...
 Ready! Mining took 30s
store header latestblock txResult: True
...
Starting new HTTP connection (1): 127.0.0.1
@@@ DONE hexHead: 00000000000000000215311ec61add2d4102bc10783e869b821b2763d836a729

**Comment by ethers** [comment]
@liberspirita You're the feeRecipient for that block header, but to get paid a fee, you or someone needs to use BTC Relay to verify a transaction, one of these:
https://blockchain.info/block-index/1109111/00000000000000000215311ec61add2d4102bc10783e869b821b2763d836a729

BTC Relay doesn't have ETH or pay out fees on its own.  When someone or a dapp uses BTC Relay, they end up paying a fee to the corresponding feeRecipient...

**Comment by ethers** [comment]
FAQ item has been added for this: http://btc-relay.readthedocs.io/en/latest/frequently-asked-questions.html#how-to-be-a-relayer-and-receive-incentives
