### ISSUE TITLE
Fee not recived

### ISSUE THREAD

**Issue by techgeek03** [ConsenSys/btcrelay-fetchd#9]
I can confirm that I'm running btcrelay successfully. I can see transactions being send to the public contract. However I never received any fee. 

`python fetchd.py -s 0xMyAddress -r 0x41f274c0023f83391de4e0733c609df5a124c3d4 -n btc --rpcHost "eth-geth01" --rpcPort 8545 --fetch -d --feeVTX 10000000000000000 --feeRecipient 0xMyAddress`

What should I do in order to receive my fee? 

This is from the log file
## @@@ 422240: 00000020d229d017ee4c3c88a9ba8571bc604e6a260109186c8e50010000000000000000e6e0fe6b65418a7716377b1083662f401bf7d1921b16a350cb5d2ade5f7cada4143e96576926051847b59948

txCount: 9
hashOne: 0000000000000000020c8abf4e79dbf156c261b18ad4c57ad8c07845f9a7b27e
hashLast: 0000000000000000020c8abf4e79dbf156c261b18ad4c57ad8c07845f9a7b27e
firstH: 00000020d229d017ee4c3c88a9ba8571bc604e6a260109186c8e50010000000000000000e6e0fe6b65418a7716377b1083662f401bf7d1921b16a350cb5d2ade5f7cada4143e96576926051847b59948
lastH: 00000020d229d017ee4c3c88a9ba8571bc604e6a260109186c8e50010000000000000000e6e0fe6b65418a7716377b1083662f401bf7d1921b16a350cb5d2ade5f7cada4143e96576926051847b59948
    Gas price: 0.0200 szabo \* 1.0000
    Our price: 20,000,000,000
store header txHash: 0x3dffd6d53ef8c1c7dd06da5deea85a3921bfcf46096b478bc1aafcfd66e7be2e
 Took 0s
store header pendingblock txResult: True
 Ready! Mining took 39s
store header latestblock txResult: True
@@@ DONE hexHead: 0000000000000000020c8abf4e79dbf156c261b18ad4c57ad8c07845f9a7b27e

**Comment by ethers** [comment]
Hi, have you read https://github.com/ethereum/btcrelay/tree/master#incentives-for-relayers ?

> The Relayer will be the getFeeRecipient() for the block they submit, and **when any transactions are verified in the block, or the header is retrieved via getBlockHeader,** the Relayer will be rewarded with getFeeAmount().

For the bold part, what is your Ethereum transaction hash that you're expecting to get the fee?

**Comment by ethers** [comment]
See also #5

**Comment by ethers** [comment]
FAQ item has been added for this: http://btc-relay.readthedocs.io/en/latest/frequently-asked-questions.html#how-to-be-a-relayer-and-receive-incentives
